# Generated by Django 5.1 on 2024-08-14 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appvaraity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='apps/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MACHINE LEARNING APP'), ('AI', 'ARTIFICIAL INTELIGENCE APP'), ('SC', 'SOCIAL MEDIA APP'), ('VI', 'VIDEO STREAMINMG APP')], max_length=2)),
            ],
        ),
    ]
